version: '3.4'

services:
  
  mongodb:
    image: mongo:4.1
    container_name: mongoprometheus
    networks:
      - networksprometeus
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser12345678
      MONGO_INITDB_ROOT_PASSWORD: mongopwd12345678

  prometheus:
    image: prom/prometheus  
    container_name: prometheus
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - networksprometeus

  mongoexporter:
    image: fabricioveronez/mongo_exporter
    container_name: mongoexporterprometheus
    ports:
      - "9216:9216" 
    networks:
      - networksprometeus
    depends_on:
      - mongodb
    environment: 
      MONGODB_URI: "mongodb://mongouser12345678:mongopwd12345678@mongodb:27017"

networks: 
  networksprometeus: 
    driver: bridge