global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
  external_labels:
    teste: "Teste-Prometheus"  

scrape_configs: 

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          grupo: "Prometheus"

  - job_name: 'mongodb_exporter'
    scrape_interval: 5s
    scrape_timeout: 1s
    static_configs:    
      - targets: ['mongoexporter:9216']
        labels:
          grupo: "MONGOEX"